sudo: required

language: node_js

node_js:
  - "6"
  - "7"

cache:
  yarn: true
  directories:
    - "node_modules"

services:
  - docker

env:
  global:
    - COMMIT=${TRAVIS_COMMIT::8}

install:
  - npm install
  - bower install
  - grunt build

after_success:
  - docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
  - export REPO=ssgdrdiot/ciotlabs-ubuntu
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
  - docker build -f Dockerfile -t $REPO:$COMMIT .
  - docker tag $REPO:$COMMIT $REPO:$TAG
  - docker tag $REPO:$COMMIT $REPO:travis-$TRAVIS_BUILD_NUMBER
  - docker push $REPO
